
package telaPrincipal;


public class Tela2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tela2.class.getName());

    public Tela2() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        rreturn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        QuantLitros = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        QuantLatas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CustoTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 290, -1));

        rreturn.setText("Recalcular");
        rreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rreturnActionPerformed(evt);
            }
        });
        getContentPane().add(rreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Àrea Total");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Quantidade de litros necessários");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        QuantLitros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantLitrosActionPerformed(evt);
            }
        });
        getContentPane().add(QuantLitros, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 290, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Quantidade de latas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        QuantLatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantLatasActionPerformed(evt);
            }
        });
        getContentPane().add(QuantLatas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 290, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Custo total");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, -1, -1));
        getContentPane().add(CustoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rreturnActionPerformed
       telaInicial inicial = new telaInicial();
    
    inicial.setLocation(this.getLocation());
    inicial.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_rreturnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    public void mostrarAreaTotal(double areaCalculada) {
    // "jTextField1" é o nome do campo que o NetBeans criou para a Área Total
    // String.format("%.2f", ...) serve para deixar com 2 casas decimais (ex: 45.50)
    jTextField1.setText(String.format("%.2f m²", areaCalculada));
}
    
    private void QuantLitrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantLitrosActionPerformed
        
    }//GEN-LAST:event_QuantLitrosActionPerformed

    private void QuantLatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantLatasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantLatasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tela2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustoTotal;
    private javax.swing.JTextField QuantLatas;
    private javax.swing.JTextField QuantLitros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton rreturn;
    // End of variables declaration//GEN-END:variables
}
